GET http://localhost:3000/todos/?status=ufvn

###
GET http://localhost:3000/todos/1/

###
GET http://localhost:3000/agenda/?date=2021-02-22

###
POST http://localhost:3000/todos/
###
PUT  http://localhost:3000/todos/2/?priority=LOW
###
DELETE http://localhost:3000/todos/6/
